# This is a basic workflow to help you get started with Actions

name: Keep mmm2020.txt uptodate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:      
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Keep Remote File Locally Up-to-date
        # You may pin to the exact commit or the version.
        # uses: TheLastProject/keep-remote-file-locally-up-to-date-action@8fb9abb447d2ea6ec8dd40c94879eb193fd6ffa0
        uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
        with: 
          # The url of the file to download
          url: https://pastebin.com/raw/VpFUqaaU
          # The location of the file in the repository to update if changed
          file_in_repo: millionmaskmarch/mmm2020.txt
          # The name of the git user
          git_user: anonymous-tld
          # The email of the git user
          git_email: info@anonymous.support
