name: Keep protests.txt uptodate
on:      
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Keep Remote File Locally Up-to-date
        uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
        with: 
          # The url of the file to download
          url: https://demo.terminkalender.top/demotermine.csv
          # The location of the file in the repository to update if changed
          file_in_repo: anticorona/protests.txt
          # The name of the git user
          git_user: anonymous-tld
          # The email of the git user
          git_email: info@anonymous.support
